AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 100
      Role: 'arn:aws:iam::436831233028:role/service-role/LF2-role-v1rl5nco'
      Layers:
        - 'arn:aws:lambda:us-east-1:436831233028:layer:LF2-dependencies:2'
